{{- if .Values.gui.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gui-{{ .Chart.Name }}
    app.kubernetes.io/component: gui-{{ .Chart.Name }}
    app.kubernetes.io/instance: gui-{{ .Release.Name }}
  name: gui-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: gui-{{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: gui-{{ .Chart.Name }}
    spec:
      containers:
      - image: {{ .Values.gui.image }}
        imagePullPolicy: IfNotPresent
        env:
        {{- toYaml .Values.gui.env | nindent 10 }}
 
        name: gui-{{ .Chart.Name }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: backend-data
          mountPath: /app/backend/data/static
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: backend-data
        emptyDir: {}
{{- end }}
